# Settings for Lelesys.SuperUser package                                        #
#                                                                               #
# Set the redirect options for Superuser when Superuser will login as user      #
# successfully or login as user falied. Also set redirect options for Superuser #
# when Superuser will logout as user.                                           #
#																																								#
#	                                                                              #
# Exapmle:                                                                      #
# 
# Lelesys:
#  SuperUser:
#    superUserRedirectOptions:
#      loginAsUserFailed:
#       roles:
#          roleName:
#            package: 'My.Admin'
#            controller: 'Admin'
#            action: 'Admin'
#      loginAsUserSuccess:
#        roles:
#          roleName:
#            package: 'My.User'
#            controller: 'User'
#           action: 'index'
#      logoutAsUser:
#         roles:
#          roleName:
#            package: 'My.Admin'
#            controller: 'Admin'
#            action: 'index'
#																				#																																							#

Lelesys:
  SuperUser:
    superUserRedirectOptions:
      loginAsUserFailed:
       roles:
          roleName:
            package: ''
            controller: ''
            action: ''
      loginAsUserSuccess:
        roles:
          roleName:
            package: ''
            controller: ''
            action: ''
      logoutAsUser:
         roles:
          roleName:
            package: ''
            controller: ''
            action: ''

    templatePathAndFilename: 'resource://Lelesys.SuperUser/Private/Templates/User/Logout.html'